site: Luis Cielak
title: "LUiS CiELAK"
description: "Product & UX Designer"
url: "https://luiscielak.github.io"
baseurl: "/lc-dot-com"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap

paginate: 7
paginate_path: "/blog/page-:num/"

logo: /images/logos/logo-lc.svg
logo_alt: /images/logos/logo-lc-alt.svg
logo_dark: /images/logos/logo-lc-dark.svg
logo_light: /images/logos/logo-lc-light.svg
favicon: /images/logos/logo-lc-favicon.svg